[package]
name = "task-manager"
version = "0.1.0"
edition = "2024"

[dependencies]
sysinfo = "0.36"
netstat2 = "0.11.1"
tui = "0.19"
crossterm = "0.29.0"
log4rs = { version = "1.3.0", features = ["config_parsing"] }
log = "0.4.27"
